"""empty message

Revision ID: 0fed0c6858a7
Revises: b62c14260d6d
Create Date: 2020-03-16 16:27:57.277939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fed0c6858a7'
down_revision = 'b62c14260d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livematch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livematch')
    # ### end Alembic commands ###
