"""empty message

Revision ID: 78426861f5e1
Revises: 3a9c5beacc1c
Create Date: 2020-03-24 18:19:14.902228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78426861f5e1'
down_revision = '3a9c5beacc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribeAll', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribeAll')
    # ### end Alembic commands ###
