"""empty message

Revision ID: 90badab54d86
Revises: 7dab5c144a7c
Create Date: 2020-03-16 01:06:53.596031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90badab54d86'
down_revision = '7dab5c144a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('user', 'passwork')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwork', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
